// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvYNj2ZCkH-_raRCJg2mAKkgtYN7RIrts',
    appId: '1:8149986184:web:2db79157b95f0fb5a3e83d',
    messagingSenderId: '8149986184',
    projectId: 'landlordconnectnotify-28483',
    authDomain: 'landlordconnectnotify-28483.firebaseapp.com',
    storageBucket: 'landlordconnectnotify-28483.appspot.com',
    measurementId: 'G-C50Q471DTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjIvvJwm7WnFIzD1lSMWh1mhbRyAg5Bs',
    appId: '1:8149986184:android:267f92c4796d83a8a3e83d',
    messagingSenderId: '8149986184',
    projectId: 'landlordconnectnotify-28483',
    storageBucket: 'landlordconnectnotify-28483.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhZZt6XvQvNxuLJOKrdrYWfh62JIqZ6e8',
    appId: '1:8149986184:ios:9e2492bcbe0e088ea3e83d',
    messagingSenderId: '8149986184',
    projectId: 'landlordconnectnotify-28483',
    storageBucket: 'landlordconnectnotify-28483.appspot.com',
    iosBundleId: 'com.keyonerealtygroup.landlordConnectHH',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhZZt6XvQvNxuLJOKrdrYWfh62JIqZ6e8',
    appId: '1:8149986184:ios:f1074c2f07db2ef5a3e83d',
    messagingSenderId: '8149986184',
    projectId: 'landlordconnectnotify-28483',
    storageBucket: 'landlordconnectnotify-28483.appspot.com',
    iosBundleId: 'com.example.landlordPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvYNj2ZCkH-_raRCJg2mAKkgtYN7RIrts',
    appId: '1:8149986184:web:41251a1f56b3948fa3e83d',
    messagingSenderId: '8149986184',
    projectId: 'landlordconnectnotify-28483',
    authDomain: 'landlordconnectnotify-28483.firebaseapp.com',
    storageBucket: 'landlordconnectnotify-28483.appspot.com',
    measurementId: 'G-6T9Y08GHPB',
  );

}